project:
  type: website
  output-dir: docs

website:
  title: "DNA Breathing in ChIP-seq and gcPBM Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    grid:
      sidebar-width: 20px
    theme: cosmo
    css: styles.css
    toc: true